// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#ifndef ROBOTMAP_H
#define ROBOTMAP_H
#include "WPILib.h"
#include "CamPIDOut.h"
#include "BSGyro.h"
#include "CrabSpeed.h"
#include "ctre\CANTalonSRX.h"
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
class RobotMap {
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static SpeedController* driveTrainFrontLeftDrive;
	static SpeedController* driveTrainFrontRightDrive;
	static SpeedController* driveTrainRearLeftDrive;
	static SpeedController* driveTrainRearRightDrive;
	static AnalogInput* driveTrainFrontLeftPos;
	static CANJaguar* driveTrainFrontLeftSteer;
	static PIDController* driveTrainFrontLeft;
	static AnalogInput* driveTrainFrontRightPos;
	static CANJaguar* driveTrainFrontRightSteer;
	static PIDController* driveTrainFrontRight;
	static AnalogInput* driveTrainRearLeftPos;
	static CANJaguar* driveTrainRearLeftSteer;
	static PIDController* driveTrainRearLeft;
	static AnalogInput* driveTrainRearRightPos;
	static CANJaguar* driveTrainRearRightSteer;
	static PIDController* driveTrainRearRight;
	static CanTalonSRX* shooterCamLeft;
	static CanTalonSRX* shooterCamRight;
	static AnalogInput* shooterCamPos;
	static AnalogInput* shooterBackupCamPos;
	static Solenoid* shooterFingers;
	static DigitalInput* shooterBallNotPresent;
	static CANJaguar* pickupBeaterBar;
	static Solenoid* pickupBeaterBarOut;
	static Solenoid* pickupWings;
	static DigitalInput* pickupBallInPickup;
	static DigitalOutput* odroidLEDSelect1;
	static DigitalOutput* odroidLEDSelect2;
	static DigitalOutput* odroidLEDSelect3;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	
	//static CANJaguar* pickupBeaterBar;
	static Gyro* driveTrainGyro;
	static CamPIDOut* shooterCamOut;
	static PIDController* shooterCamController;
//	static PIDController* shooterBackupCamController;
	
	static CrabSpeed* CrabSpeedTwist;
	
	static PIDController* driveTrainDriveControlTwist;
	
	static void init();
};
#endif
